<html>
 <head></head>
 <body>
  <p>Your program will have an access to <b>foo</b> function, which can throw exceptions.</p> 
  <p>You need to write a code, which launches this function and than catches the <b>ArithmeticError, AssertionError, ZeroDivisionError</b>&nbsp;exceptions and outputs the name of the caught exception.</p> 
  <p>An example of the solution, which you need to send for checking.</p> 
  <pre><code class="language-python">try:
    foo()
except Exception:
    print("Exception")
except BaseException:
    print("BaseException")</code></pre> 
  <p>Hint: see <a href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy" rel="nofollow noopener noreferrer">https://docs.python.org/3/library/exceptions.html#exception-hierarchy</a></p>
 </body>
</html><br><br><font color="gray">Memory limit: 256 Mb</font><br><font color="gray">Time limit: 2s</font><br><br>